---
title: "Getting html"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting html}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Just get some html

In this vignette we go through the process of getting some html files First we need to set-up a tibble of papers that we are interested in.

```{r, eval = FALSE}
library(heapsofpapers)

two_websites <-
  tibble::tibble(
    locations_are = c("https://en.wikipedia.org/wiki/List_of_prime_ministers_of_Australia",
                      "https://en.wikipedia.org/wiki/List_of_prime_ministers_of_Canada"),
    save_here = c("australian_pms.html",
                  "canadian_pms.html")
  )
```

Now we want to download those PDFs (this will just download them into the current working directory).

```{r, eval = FALSE}
heapsofpapers::get_and_save(
  data = two_websites,
  links = "locations_are",
  save_names = "save_here"
)
```


